- hosts: jumpbox
  gather_facts: false
  vars:
    webserver_name: web3
    deployment: dev
  tasks:
  - name: check active servers
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  - name: Remove a server instance
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      meta: "deployment_name={{ deployment }}"
      state: absent
    with_items: "{{ result.ansible_facts.openstack_servers }}"
